### ISSUE TITLE
MySQL Cluster could not be connected

### ISSUE THREAD

**Issue by sgc-fireball** [shopware/platform#11085]
### Shopware Version

6.7.0.0

### Affected area / extension

Platform(Default)

### Actual behaviour

Every where you can found an `PDOException {#66 #message: "SQLSTATE[HY000] [2002] No such file or directory"`.

### Expected behaviour

I can open the storefront and admin backend and i can run console commands.

### How to reproduce

1. Install Shopware 6.7 using pdo_mysql
2. ENV with
  ```env
  DATABASE_URL=mysql://shopware:shopware@mysql:3306/shopware
  DATABASE_REPLICA_0_URL=mysql://shopware:shopware@mysql:3306/shopware
  ```
3. Open any page or run an command.

*Analyses*
The Method `\Shopware\Core\Framework\Adapter\Database\MySQLFactory::create` receives all necessary informations. The parser works well.

The `$parameters` contains an array with host, port, user, password, primary[0], replica[0].
BUT the both variables primary[0], replica[0] doesn't contains the user or password, they have only the `url` value with a DSN.

The method `\Doctrine\DBAL\DriverManager::getConnection` received the `PrimaryReadReplicaConnection` and in the deepest level in `PrimaryReadReplicaConnection`:231i could not found any username or password. Here i can see the primary[0] with charset, and driver class.

I think the primary[0] must me parsed before we are reaching this point.

### Definition of Done

- [ ] An automated test covers the fix.
- [ ] Integration/E2E testing in staging is done.
- [ ] Changelog markdown file created or updated in /changelog/_unreleased directory.
- [ ] Developer documentation written/updated.
- [ ] End user and/or developer documentation written or updated with clarification.
- [ ] Regression test created to ensure bug does not reappear, and automated regression tests pass.
- [ ] Code changes resolve the reported bug without introducing new issues.

**Comment by h1k3r** [comment]
Hey @sgc-fireball,

Thanks for the report and your analysis!

The fix is already available here: https://github.com/shopware/shopware/pull/11111 — feel free to check if it works in your environment.

**Comment by h1k3r** [comment]
There will be no 6.7.0 releases, so backport is not possible. Fixed in 6.7.1.

**Comment by em-job** [comment]
Hi @h1k3r,
I'm still experiencing this issue with SW 6.7.1. I believe #11111 only fixes it for the replicas, but the primary array key is still missing credentials like user, password, etc. In my case, applying an array_merge—as it's done for the replicas—solves the issue.
before:
`            $parameters['primary'] = ['url' => $url, 'driverOptions' => $parameters['driverOptions']];
`
after:

`
$parameters['primary'] = array_merge([
                'charset' => $parameters['charset'],
                'driverOptions' => $parameters['driverOptions'],
                'url' => $url,
            ], $parameters);
`

in src/Core/Framework/Adapter/Database/MySQLFactory.php

**Comment by h1k3r** [comment]
Hi @em-job ,

thanks for reporting this! I can confirm the issue, the primary connection is not initialized properly and any write to the database causes an error.

This pr should fix the problem: https://github.com/shopware/shopware/pull/11594
