### ISSUE TITLE
Broken cart table after update to 6.4.2.0

### ISSUE THREAD

**Issue by xrogers** [shopware/platform#1961]
### PHP Version

8.0.8

### Shopware Version

6.4.2.0

### Expected behaviour

Dump from the shop should be usable / possible to import.
Constraints on the columns should be valid.

### Actual behaviour

Import of the dump breaks with error:

> ERROR 4025 (23000) at line 6046: CONSTRAINT `cart.rule_ids` failed for `shopware`.`cart`

rule_ids column contains empty string values.

### How to reproduce

Update shop with version <6.4.2.0 with carts in the database.
Try to dump database and import the newly created dump.

**Comment by Schrank** [comment]
Fixed in 6.4.2.1 (at least, that is my assumption with https://www.shopware.com/en/changelog/#6-4-2-1)

**Comment by mitelg** [comment]
@Schrank we did not fix something with rules 😬 (see https://github.com/shopware/platform/commit/723674d20a52880ba2a3929d41422272138068a2 )
I guess this is another error
@shyim can you have a look? 🙈

**Comment by xrogers** [comment]
> 
> 
> Fixed in 6.4.2.1 (at least, that is my assumption with https://www.shopware.com/en/changelog/#6-4-2-1)

Nope, it wasn't fixed.
The dirty solution would be another migration like:
`update cart set rule_ids = '[]' where rule_ids = ''`, but it could break the logic depending on the value in this field.

**Comment by Schrank** [comment]
Sorry for the wrong info @xrogers

**Comment by shyim** [comment]
Thanks. I could reproduce this. I will talk internally what we do as next steps and come back here.

**Comment by shyim** [comment]
Is fixed in trunk
