### ISSUE TITLE
grand/grant_type typo

### ISSUE THREAD

**Issue by apapsch** [shopware/platform#2240]
### PHP Version

any

### Shopware Version

any

### Expected behaviour

In the [OAuth 2.0 access token endpoint](https://shopware.stoplight.io/docs/admin-api/b3A6MTMzMTcwNzc-fetch-an-access-token) there should be a parameter named `grant_type`.

### Actual behaviour

The parameter is misspelled (`grand_type`), making it incompatible with existing OAuth libraries.

### How to reproduce

1. On the docs page linked above, copy the curl code.
2. Change `grand` to `grant`.
3. Submit the request.

The error response will reliably say "The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed.".

**Comment by shyim** [comment]
I am very sure we fixed this already :thinking:

**Comment by apapsch** [comment]
OK, I assumed `any` (released) version because it's still shown on the docs page.

**Comment by apapsch** [comment]
I checked with latest version `6.4.7.0` and it exhibits the same behavior:

Request with `grant_type` returns:

```
{"errors":[{"code":"3","status":"400","title":"The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed.","detail":"Check the `client_id` parameter"}]}
```

With `grand_type`:

```
{"errors":[{"code":"2","status":"400","title":"The authorization grant type is not supported by the authorization server.","detail":"Check that all required parameters have been provided"}]}
```

Previously, I overlooked the tiny bit `"detail":"Check the `client_id` parameter"` in the first response (the other server has dev mode enabled and it returns a long backtrace). Therefore I guess Shopware does things alright, it's just the docs that need and update.

**Comment by shyim** [comment]
The documentation is wrong. I will look how we can update spotlight

**Comment by shyim** [comment]
it has been corrected
