### ISSUE TITLE
documents reference orders LIVE_VERSION

### ISSUE THREAD

**Issue by MalteJanz** [shopware/platform#8031]
### PHP Version

8.2

### Shopware Version

6.6.10.2

### Affected area / extension

Extension:Commercial

### Actual behaviour

After creating a few documents for an order:
![Image](https://github.com/user-attachments/assets/1d03d163-0f42-43c4-81c9-7dedeb0eb7b1)

They end up like this in the database:
![Image](https://github.com/user-attachments/assets/02c889ca-6681-4001-bc5b-134437dad122)
used query:
```SQL
SELECT document_type.technical_name, document.order_id, document.order_version_id
FROM `document`, document_type
WHERE document.document_type_id = document_type.id;
```

The following documents created a unique and persistent version of the order at the time the document was generated (this is the expected behavior):
- `invoice`
- `zugferd_embedded_invoice`
- `storno`

But the following are referencing the `LIVE_VERSION` of the order (`0x0FA91CE3E96A4BC2BE4BD9CE752C3425`):
- `delivery_note`
- `zugferd_invoice`
- `partial_cancellation`

### Expected behaviour

Documents should always reference a newly created version of the order at that point in time to make it consistent.

### How to reproduce

Just create all possible documents in a order (ideally with SwagCommercial installed + License to have all document types).

**Comment by MalteJanz** [comment]
Discovered in Dev-Support case: 
#SWAG-298692

We should make sure the fix gets backported to all relevant versions

**Comment by MalteJanz** [comment]
Handover from @ennasus4sun :
platform part of this issue should be fixed with https://github.com/shopware/shopware/pull/8335
But SwagCommercial still needs a fix for `partial_cancellation` documents

internal handover slack: https://shopware-ag.slack.com/archives/C05QHLTM1TN/p1744380778628959?thread_ts=1744378843.815349&cid=C05QHLTM1TN

**Comment by winniae** [comment]
(Hi, I'm new to contributing, so excuse if I'm not following the correct bug reporting procedures..? Should I better just submit Pull-Requests if I can?)

I'm just experimenting with documents and the order_version_id...
I believe the **credit_note** should also generate and reference a new order_version.

Right now, the order_version_id of a credit note is set to the LIVE_VERSION. While the referenced_document_id points to the invoice correctly, which also has the correct order_version_id, it is useless to re-instantiate the relevant credit_line_items that lead to the creation of the credit_note document.


I would love to see this fixed in 6.5.8.x
Also updating a document in 6.5.8.x sets the overwrites the order_version_id to the live_version as I reported in
https://github.com/shopware/shopware/issues/8391

**Comment by iwv-stefan-m** [comment]
Hello,

We are still experiencing issues with the latest version of Shopware Commercial.

- When an order with `tax_status` set to `gross` is created, the `shipping_costs` in the order_return table are incorrectly stored as net values. I’ve attached two screenshots to illustrate the difference between the correct data in the order table and the incorrect data in the `order_return` table.
- In some cases, the calculated taxes for shipping costs are not handled correctly. After a partial cancellation is created, these calculated taxes  are set to 0.

### Order Table
![Orders Table](https://github.com/user-attachments/assets/6a0789bb-acf6-413d-9363-416f4746b8b9)

### Order Return Table
![Image](https://github.com/user-attachments/assets/25f573a9-b5eb-41d6-a386-56b3a0874991)

https://github.com/user-attachments/assets/8315333b-a9ed-453f-abe0-76a4c3a34fcd

**Comment by iwv-stefan-m** [comment]
@MalteJanz

**Comment by MalteJanz** [comment]
Hi @iwv-stefan-m , thanks for reaching out. Could you please create a new bug issue about this? To us it looks like a different issue than the original, that was about missing order versions / always referencing live versions. Your issue seems to be about order returns and the calculated taxes (inside the document and in the DB / admin)
