### ISSUE TITLE
Missing Backport: Language Dropdown text alignment and size

### ISSUE THREAD

**Issue by ravenokko** [shopware/platform#8924]
### Technical TODO

The language dropdown in listing overviews (Products/Orders/Customers/Shopping Experiences, etc) has misaligned text and is too large in `6.7.0.0` but is fixed in `trunk`. I struggled to find an issue/PR for this, so could someone please confirm if these fixes were/will be backported 🙂 

<img width="1024" alt="Image" src="https://github.com/user-attachments/assets/14ba5f8e-4c26-4d40-8961-e98382fea6d1" />

**Comment by jleifeld** [comment]
FYI: It was fixed together with this PR:

https://github.com/shopware/shopware/pull/8177/files#diff-b8e56fba43af1c19c2a47cbdecf3c8f286af40d29508a5c2ff85850735635b19R11

I will create a backport for this fix.

**Comment by ravenokko** [comment]
Language dropdown is still not center aligned in Products/Customers/Shopping Experiences overviews
Notes + screenshots: [SW 6: Test Documentation 6.7.0.0-QA](https://shopware.atlassian.net/wiki/spaces/CORE/pages/edit-v2/20354629633#%5BhardBreak%5DAdmin-UI-Issues-found-during-RC4-testing)

**Comment by ravenokko** [comment]
> Language dropdown is still not center aligned in Products/Customers/Shopping Experiences overviews Notes + screenshots: [SW 6: Test Documentation 6.7.0.0-QA](https://shopware.atlassian.net/wiki/spaces/CORE/pages/edit-v2/20354629633#%5BhardBreak%5DAdmin-UI-Issues-found-during-RC4-testing)

Closing this and creating a new ticket.
