### ISSUE TITLE
B2B Components offers can only be created when the customer is logged in

### ISSUE THREAD

**Issue by jschael-sw** [shopware/platform#9144]
### Shopware Version

6.6.10.3

### Affected area / extension

Platform(Default)

### Actual behaviour

As soon as you want to create a quote with components for a customer, an error is thrown that the customer is not logged in.  
This is not useful because you also want to create offers without the customer being logged in.

### Expected behaviour

Offers can also be made to customers who are not logged in

### How to reproduce

Assign quotation management to customers and try to send them a quotation without them being logged in.

**Comment by leduc92** [comment]
Hi @jschael-sw could you please check again the issue with 6.6.10.4. The issue has been fixed by this version.

**Comment by konstantinkoeppe** [comment]
Hello, in our environment the issue still seems to be present even with 6.6.10.4.

![Image](https://github.com/user-attachments/assets/8fe57800-c111-4b71-b7ca-e968be2d9a02)

Is there anything we could do or information to provide to assist with this?

**Comment by konstantinkoeppe** [comment]
I believe I found the underlying reason for this issue:

In the `Shopware\Commercial\B2B\QuoteManagement\Domain\Admin\Api\QuoteActionController` the method `getContextTokenFromCustomer` attempts to fetch an existing context token by customer id like this:

```sql
SELECT token FROM sales_channel_api_context WHERE customer_id = :customerId
```

There is no filter by sales channel id, so if the customer is using multiple sales channels and thus the query finds multiple results and simply takes the first one (`->fetchOne`) it might not match the sales channel we are currently trying to create a quote for.

Could you maybe take another look at this @leduc92?
